// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: livekit_agent.proto

package livekit

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ======================
// AgentService Interface
// ======================

type AgentService interface {
	CheckEnabled(context.Context, *CheckEnabledRequest) (*CheckEnabledResponse, error)

	CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error)
}

// ============================
// AgentService Protobuf Client
// ============================

type agentServiceProtobufClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAgentServiceProtobufClient creates a Protobuf client that implements the AgentService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewAgentServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) AgentService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "livekit", "AgentService")
	urls := [2]string{
		serviceURL + "CheckEnabled",
		serviceURL + "CheckAvailability",
	}

	return &agentServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *agentServiceProtobufClient) CheckEnabled(ctx context.Context, in *CheckEnabledRequest) (*CheckEnabledResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentService")
	ctx = ctxsetters.WithMethodName(ctx, "CheckEnabled")
	caller := c.callCheckEnabled
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CheckEnabledRequest) (*CheckEnabledResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CheckEnabledRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CheckEnabledRequest) when calling interceptor")
					}
					return c.callCheckEnabled(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CheckEnabledResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CheckEnabledResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentServiceProtobufClient) callCheckEnabled(ctx context.Context, in *CheckEnabledRequest) (*CheckEnabledResponse, error) {
	out := new(CheckEnabledResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentServiceProtobufClient) CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentService")
	ctx = ctxsetters.WithMethodName(ctx, "CheckAvailability")
	caller := c.callCheckAvailability
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CheckAvailabilityRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CheckAvailabilityRequest) when calling interceptor")
					}
					return c.callCheckAvailability(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CheckAvailabilityResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CheckAvailabilityResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentServiceProtobufClient) callCheckAvailability(ctx context.Context, in *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	out := new(CheckAvailabilityResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// AgentService JSON Client
// ========================

type agentServiceJSONClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAgentServiceJSONClient creates a JSON client that implements the AgentService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewAgentServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) AgentService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "livekit", "AgentService")
	urls := [2]string{
		serviceURL + "CheckEnabled",
		serviceURL + "CheckAvailability",
	}

	return &agentServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *agentServiceJSONClient) CheckEnabled(ctx context.Context, in *CheckEnabledRequest) (*CheckEnabledResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentService")
	ctx = ctxsetters.WithMethodName(ctx, "CheckEnabled")
	caller := c.callCheckEnabled
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CheckEnabledRequest) (*CheckEnabledResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CheckEnabledRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CheckEnabledRequest) when calling interceptor")
					}
					return c.callCheckEnabled(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CheckEnabledResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CheckEnabledResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentServiceJSONClient) callCheckEnabled(ctx context.Context, in *CheckEnabledRequest) (*CheckEnabledResponse, error) {
	out := new(CheckEnabledResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentServiceJSONClient) CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentService")
	ctx = ctxsetters.WithMethodName(ctx, "CheckAvailability")
	caller := c.callCheckAvailability
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CheckAvailabilityRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CheckAvailabilityRequest) when calling interceptor")
					}
					return c.callCheckAvailability(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CheckAvailabilityResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CheckAvailabilityResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentServiceJSONClient) callCheckAvailability(ctx context.Context, in *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	out := new(CheckAvailabilityResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// AgentService Server Handler
// ===========================

type agentServiceServer struct {
	AgentService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewAgentServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewAgentServiceServer(svc AgentService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &agentServiceServer{
		AgentService:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *agentServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *agentServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// AgentServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const AgentServicePathPrefix = "/twirp/livekit.AgentService/"

func (s *agentServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "livekit.AgentService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "CheckEnabled":
		s.serveCheckEnabled(ctx, resp, req)
		return
	case "CheckAvailability":
		s.serveCheckAvailability(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *agentServiceServer) serveCheckEnabled(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCheckEnabledJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCheckEnabledProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *agentServiceServer) serveCheckEnabledJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CheckEnabled")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CheckEnabledRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AgentService.CheckEnabled
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CheckEnabledRequest) (*CheckEnabledResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CheckEnabledRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CheckEnabledRequest) when calling interceptor")
					}
					return s.AgentService.CheckEnabled(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CheckEnabledResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CheckEnabledResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CheckEnabledResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CheckEnabledResponse and nil error while calling CheckEnabled. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentServiceServer) serveCheckEnabledProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CheckEnabled")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CheckEnabledRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AgentService.CheckEnabled
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CheckEnabledRequest) (*CheckEnabledResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CheckEnabledRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CheckEnabledRequest) when calling interceptor")
					}
					return s.AgentService.CheckEnabled(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CheckEnabledResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CheckEnabledResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CheckEnabledResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CheckEnabledResponse and nil error while calling CheckEnabled. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentServiceServer) serveCheckAvailability(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCheckAvailabilityJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCheckAvailabilityProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *agentServiceServer) serveCheckAvailabilityJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CheckAvailability")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CheckAvailabilityRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AgentService.CheckAvailability
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CheckAvailabilityRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CheckAvailabilityRequest) when calling interceptor")
					}
					return s.AgentService.CheckAvailability(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CheckAvailabilityResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CheckAvailabilityResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CheckAvailabilityResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CheckAvailabilityResponse and nil error while calling CheckAvailability. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentServiceServer) serveCheckAvailabilityProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CheckAvailability")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CheckAvailabilityRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AgentService.CheckAvailability
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CheckAvailabilityRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CheckAvailabilityRequest) when calling interceptor")
					}
					return s.AgentService.CheckAvailability(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CheckAvailabilityResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CheckAvailabilityResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CheckAvailabilityResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CheckAvailabilityResponse and nil error while calling CheckAvailability. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor5, 0
}

func (s *agentServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *agentServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "livekit", "AgentService")
}

var twirpFileDescriptor5 = []byte{
	// 1629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x26, 0x00, 0x52, 0x24, 0x9b, 0x3f, 0xa6, 0x46, 0x92, 0x97, 0xab, 0x5d, 0xef, 0x4a, 0xd8,
	0xa4, 0xac, 0x55, 0x62, 0xb9, 0xa2, 0xe4, 0xe0, 0x68, 0x77, 0x2b, 0x21, 0xb5, 0x72, 0x48, 0x5a,
	0x92, 0xe5, 0xa1, 0x14, 0x57, 0xf9, 0x82, 0x02, 0x89, 0x31, 0x05, 0x09, 0xc0, 0x20, 0x98, 0xa1,
	0x5c, 0xba, 0xe5, 0x90, 0x43, 0x5e, 0x21, 0x87, 0x5c, 0x72, 0xcc, 0x0b, 0xe4, 0x98, 0x1c, 0xf3,
	0x04, 0xa9, 0x1c, 0xf2, 0x04, 0x79, 0x8a, 0xd4, 0x0c, 0x06, 0x3f, 0xfc, 0x73, 0x54, 0x7b, 0xe3,
	0xf4, 0x1f, 0x66, 0xfa, 0xeb, 0xfe, 0xba, 0x25, 0xd8, 0xf0, 0xdc, 0x3b, 0x72, 0xeb, 0x72, 0xcb,
	0x9e, 0x90, 0x80, 0x1f, 0x84, 0x11, 0xe5, 0x14, 0x95, 0x95, 0x70, 0x7b, 0x33, 0xd1, 0xfa, 0xd4,
	0x21, 0x1e, 0x8b, 0xd5, 0xe6, 0xbf, 0x74, 0x30, 0x06, 0x74, 0x84, 0x9a, 0xa0, 0xbb, 0x4e, 0x5b,
	0xdb, 0xd1, 0xf6, 0xaa, 0x58, 0x77, 0x1d, 0xf4, 0x25, 0xd4, 0x1c, 0x97, 0x85, 0x36, 0x1f, 0x5f,
	0x5b, 0xae, 0xd3, 0xae, 0x4a, 0x05, 0x24, 0xa2, 0xbe, 0x83, 0x7e, 0x04, 0x45, 0x7e, 0x1f, 0x92,
	0xb6, 0xbe, 0xa3, 0xed, 0x35, 0x0f, 0x5b, 0x07, 0x2a, 0xfa, 0xc1, 0x80, 0x8e, 0x2e, 0xef, 0x43,
	0x82, 0xa5, 0x16, 0xed, 0x42, 0x31, 0xa2, 0xd4, 0x6f, 0x1b, 0x3b, 0xda, 0x5e, 0xed, 0xb0, 0x91,
	0x5a, 0x61, 0x4a, 0x7d, 0x2c, 0x55, 0xe8, 0x57, 0x50, 0x0b, 0xed, 0x88, 0xbb, 0x63, 0x37, 0xb4,
	0x03, 0xde, 0x2e, 0x4a, 0xcb, 0x76, 0x6a, 0x79, 0x91, 0xe9, 0xfa, 0xc1, 0x7b, 0xda, 0x2b, 0xe0,
	0xbc, 0xf9, 0x1f, 0x35, 0x0d, 0xed, 0x40, 0x35, 0xb0, 0x7d, 0xc2, 0x42, 0x7b, 0x4c, 0xda, 0x25,
	0x71, 0xd1, 0xae, 0xde, 0xd6, 0x70, 0x26, 0x44, 0xdb, 0x50, 0xf1, 0x09, 0xb7, 0x1d, 0x9b, 0xdb,
	0xed, 0x35, 0xf9, 0x92, 0xf4, 0x8c, 0x9e, 0x00, 0xc8, 0x74, 0x59, 0xc2, 0xbc, 0x5d, 0x96, 0xda,
	0xaa, 0x94, 0x9c, 0xdb, 0x3e, 0x41, 0x4f, 0xa1, 0xc4, 0xb8, 0xcd, 0x49, 0xbb, 0x22, 0xef, 0xb5,
	0x9e, 0x7f, 0xe7, 0x50, 0x28, 0x70, 0xac, 0xef, 0x36, 0xa1, 0x6e, 0xe5, 0x2e, 0x66, 0xfe, 0x5b,
	0x83, 0x4a, 0x62, 0x83, 0xf6, 0x61, 0x4d, 0x58, 0x4d, 0x99, 0xcc, 0x70, 0xf3, 0x10, 0xcd, 0x87,
	0x99, 0x32, 0xac, 0x2c, 0xd0, 0x26, 0x94, 0x48, 0x14, 0xd1, 0x48, 0x66, 0xb6, 0x8a, 0xe3, 0x83,
	0xb8, 0x26, 0xe3, 0x76, 0xc4, 0x89, 0x63, 0xd9, 0x5c, 0xa6, 0xd3, 0xc0, 0x55, 0x25, 0xe9, 0x70,
	0xf4, 0x29, 0x54, 0x48, 0xe0, 0xc4, 0xca, 0xa2, 0x54, 0x96, 0xe5, 0xb9, 0xc3, 0x85, 0xe7, 0x34,
	0x74, 0x6c, 0xe5, 0x59, 0x8a, 0x3d, 0x95, 0xa4, 0xc3, 0xd1, 0xcf, 0x60, 0x33, 0x77, 0x6d, 0xcb,
	0x75, 0x48, 0xc0, 0x5d, 0x7e, 0xaf, 0xf2, 0xb4, 0x91, 0xd3, 0xf5, 0x95, 0xca, 0xfc, 0x8b, 0x0e,
	0xf0, 0x96, 0x46, 0xb7, 0x24, 0x12, 0x88, 0x2c, 0x94, 0xce, 0x6c, 0x46, 0xf5, 0xf9, 0x8c, 0xb6,
	0xa1, 0x7c, 0x47, 0x22, 0xe6, 0xd2, 0x40, 0x3e, 0xa3, 0x8a, 0x93, 0x23, 0x7a, 0x96, 0x66, 0xa9,
	0x28, 0xb3, 0xb4, 0x95, 0x66, 0x29, 0xfe, 0xda, 0x5c, 0xa2, 0xf2, 0xa8, 0x96, 0xe6, 0x50, 0x45,
	0x50, 0xf4, 0xa8, 0xed, 0xc8, 0x57, 0xe8, 0x58, 0xfe, 0x46, 0x9f, 0x41, 0xf5, 0x86, 0x8e, 0xac,
	0x31, 0x9d, 0x06, 0x5c, 0x02, 0xdd, 0xc0, 0x95, 0x1b, 0x3a, 0x3a, 0x16, 0x67, 0xf4, 0x1a, 0x36,
	0x6c, 0xcf, 0xa3, 0x1f, 0x88, 0x63, 0x85, 0x24, 0xf2, 0x5d, 0x26, 0x6e, 0xc4, 0x14, 0xea, 0x5f,
	0x2c, 0xab, 0xc6, 0x8b, 0xd4, 0x0c, 0x23, 0xe5, 0x9a, 0x89, 0x98, 0xf9, 0x4f, 0x03, 0x1a, 0xf1,
	0xb5, 0xcf, 0x08, 0x63, 0xf6, 0x84, 0xa0, 0x6f, 0xa1, 0x12, 0x91, 0x89, 0xcb, 0x38, 0x89, 0x64,
	0xb6, 0xf2, 0x71, 0xb1, 0x52, 0xc4, 0x1e, 0x98, 0xfc, 0x6e, 0x4a, 0x18, 0xef, 0x15, 0x70, 0xea,
	0x81, 0x8e, 0xa1, 0x6e, 0xdf, 0xd9, 0xae, 0x67, 0x8f, 0x5c, 0x4f, 0xe0, 0xa3, 0xcb, 0x08, 0x4f,
	0xd2, 0x08, 0x9d, 0x9c, 0x12, 0x13, 0x16, 0xd2, 0x80, 0x91, 0x5e, 0x01, 0xcf, 0x38, 0xa1, 0x2e,
	0x34, 0x62, 0xe4, 0xad, 0x0f, 0xf2, 0x43, 0xaa, 0x2f, 0x3f, 0x4b, 0xa3, 0x5c, 0x49, 0x6d, 0x3e,
	0xdd, 0x22, 0xc6, 0x34, 0x27, 0x45, 0xbf, 0x4c, 0xea, 0xc9, 0xba, 0xa1, 0xa3, 0x85, 0x76, 0x8d,
	0x03, 0xa4, 0x55, 0xdd, 0x2b, 0x24, 0xb5, 0x26, 0x48, 0xe6, 0x6b, 0x28, 0x86, 0x6e, 0x30, 0x91,
	0x68, 0xd5, 0x0e, 0x37, 0xe6, 0xe0, 0xbd, 0x70, 0x83, 0x49, 0xaf, 0x80, 0xa5, 0x09, 0xfa, 0x35,
	0xd4, 0x99, 0xeb, 0x4f, 0xbd, 0xe4, 0x3b, 0x6b, 0x73, 0x17, 0x1d, 0x2a, 0xe5, 0x80, 0x8e, 0xb2,
	0x6c, 0xd5, 0x58, 0x26, 0x45, 0xdf, 0x41, 0xcd, 0x77, 0x27, 0x51, 0x12, 0xa0, 0x2c, 0x03, 0x6c,
	0xa7, 0x01, 0xce, 0x62, 0xdd, 0x8c, 0x3f, 0xf8, 0xa9, 0xb0, 0x5b, 0x85, 0xb2, 0x1f, 0x03, 0x67,
	0xfe, 0x5d, 0x87, 0xc6, 0x90, 0x44, 0x77, 0x19, 0x94, 0xdf, 0x2d, 0x40, 0xf9, 0xe5, 0x4a, 0x28,
	0x53, 0x28, 0x32, 0x2c, 0xbb, 0x4b, 0xb1, 0xfc, 0x7c, 0x05, 0x96, 0xc9, 0xed, 0x66, 0xa1, 0x7c,
	0x01, 0x60, 0x33, 0xe6, 0x4e, 0x02, 0x9f, 0x04, 0x5c, 0xe1, 0xf8, 0x38, 0x4f, 0x2b, 0x9d, 0x54,
	0x2b, 0x5e, 0x96, 0xd9, 0xa2, 0x6f, 0xa0, 0xc6, 0x45, 0xa1, 0x06, 0x36, 0x17, 0x4d, 0x18, 0x83,
	0xf1, 0xc9, 0x0c, 0x81, 0x67, 0x6a, 0x91, 0xd5, 0x9c, 0xb5, 0x84, 0x90, 0x06, 0x13, 0x85, 0xfb,
	0x02, 0x84, 0x54, 0x41, 0x48, 0x83, 0x49, 0x3e, 0x83, 0x7f, 0xd2, 0x00, 0x2d, 0x22, 0x96, 0xce,
	0x10, 0xed, 0x41, 0x33, 0x44, 0x5f, 0x3d, 0x43, 0x8e, 0x66, 0x67, 0x88, 0xf1, 0xf1, 0x19, 0x32,
	0x33, 0x41, 0xcc, 0xfd, 0x84, 0xcc, 0x44, 0xfd, 0xa1, 0xcf, 0xa1, 0xca, 0x5d, 0x9f, 0x30, 0x6e,
	0xfb, 0xa1, 0xbc, 0x97, 0x81, 0x33, 0x81, 0xf9, 0x26, 0xb5, 0xa5, 0xc1, 0x04, 0xfd, 0x18, 0x9a,
	0x9e, 0xcd, 0xb8, 0x35, 0xef, 0xd0, 0x10, 0xd2, 0xcb, 0x44, 0x38, 0x1b, 0x52, 0x9f, 0x0f, 0xf9,
	0x67, 0x1d, 0xb6, 0x96, 0x76, 0xff, 0x03, 0xb3, 0x33, 0xcb, 0xb6, 0x95, 0x87, 0xb3, 0xed, 0x57,
	0xd0, 0x10, 0x9d, 0x66, 0xb9, 0x01, 0x27, 0xd1, 0x9d, 0xed, 0xc9, 0x42, 0x68, 0xe0, 0xba, 0x10,
	0xf6, 0x95, 0x0c, 0xed, 0xe6, 0x67, 0xab, 0x1c, 0x09, 0xa2, 0xa3, 0x53, 0x91, 0x18, 0xbf, 0x2b,
	0x98, 0xb3, 0xfc, 0x43, 0x99, 0xb3, 0x5b, 0x07, 0xb0, 0xd2, 0x2f, 0x98, 0xb7, 0xf0, 0x78, 0x79,
	0x47, 0x09, 0x3e, 0x8f, 0x59, 0xcc, 0x4a, 0xc7, 0x4f, 0x25, 0x16, 0xf4, 0x1d, 0xf4, 0x0b, 0xa8,
	0x31, 0xd9, 0xb2, 0x96, 0x1b, 0xbc, 0xa7, 0xaa, 0x22, 0xb2, 0x72, 0x8d, 0xdb, 0x59, 0x16, 0x03,
	0xb0, 0xf4, 0xb7, 0xf9, 0x53, 0x58, 0x5f, 0xe0, 0x05, 0xf4, 0x09, 0x94, 0xc5, 0xdc, 0x70, 0x1d,
	0xd6, 0xd6, 0x77, 0x8c, 0xbd, 0x2a, 0x5e, 0xbb, 0xa1, 0xa3, 0xbe, 0xc3, 0xcc, 0x37, 0xb0, 0xb1,
	0xa4, 0x53, 0xd1, 0x17, 0x60, 0x08, 0xc2, 0x89, 0x79, 0xa1, 0x9e, 0x87, 0x0d, 0x0b, 0x85, 0x98,
	0x5b, 0x11, 0x61, 0x53, 0x5f, 0x30, 0xa1, 0x28, 0x87, 0x0a, 0x4e, 0xcf, 0xe6, 0x3f, 0x0c, 0xd8,
	0x5c, 0xc6, 0xe4, 0x68, 0x0b, 0xd6, 0xe2, 0x4b, 0xa8, 0x97, 0x96, 0xe4, 0x1d, 0x44, 0x6d, 0x29,
	0x56, 0xf0, 0x88, 0x0a, 0x96, 0x09, 0xd0, 0x53, 0x78, 0xc4, 0xa6, 0x61, 0x48, 0x23, 0xce, 0x2c,
	0xf9, 0x09, 0x22, 0x13, 0x51, 0xc1, 0xcd, 0x44, 0x8c, 0xa5, 0x14, 0x7d, 0x0d, 0xad, 0xfc, 0x12,
	0x20, 0x4b, 0xa9, 0x28, 0xbf, 0xf3, 0x28, 0x27, 0x97, 0x05, 0xb5, 0x6a, 0x5f, 0x28, 0xad, 0xdc,
	0x17, 0xe6, 0x5d, 0xe6, 0x56, 0xb1, 0xbc, 0xcb, 0x59, 0x32, 0xbf, 0x29, 0x3c, 0xce, 0xbb, 0xd8,
	0x9c, 0x47, 0xee, 0x68, 0xca, 0x89, 0xa8, 0x2b, 0x63, 0xaf, 0x76, 0xf8, 0xe2, 0xa3, 0x73, 0x2f,
	0x5f, 0x6c, 0x9d, 0xd4, 0xf5, 0x24, 0xe0, 0xd1, 0x3d, 0xde, 0x0a, 0x97, 0xe9, 0xb6, 0x7b, 0xb0,
	0xbd, 0xda, 0x09, 0xb5, 0xc0, 0xb8, 0x25, 0xf7, 0x2a, 0xf5, 0xe2, 0xa7, 0xd8, 0xd2, 0xee, 0x6c,
	0x6f, 0x9a, 0xec, 0x37, 0xf1, 0xe1, 0x48, 0x7f, 0xa1, 0x99, 0x37, 0xf0, 0x68, 0x6e, 0x08, 0xae,
	0x02, 0x2f, 0xdb, 0x0a, 0xf5, 0x87, 0x6f, 0x85, 0x46, 0x6e, 0x2b, 0x34, 0xff, 0xa0, 0x01, 0x5a,
	0x1c, 0xd9, 0xe8, 0x70, 0x6e, 0xdd, 0x5c, 0xbe, 0x48, 0xf5, 0x0a, 0x49, 0x74, 0xd1, 0xc6, 0xc9,
	0xc6, 0x64, 0xac, 0xda, 0x98, 0x8a, 0xb3, 0x1b, 0x93, 0xa0, 0x77, 0x2b, 0x76, 0x37, 0x1d, 0x68,
	0xcc, 0x0c, 0x9c, 0xff, 0xdb, 0x02, 0x5b, 0x60, 0x4c, 0x23, 0x2f, 0xce, 0x5d, 0xaf, 0x80, 0xc5,
	0x41, 0xdc, 0x61, 0x13, 0x4a, 0x9c, 0xde, 0x92, 0x84, 0xaa, 0xe2, 0x43, 0x77, 0x0d, 0x8a, 0xd6,
	0x34, 0xf2, 0xcc, 0xa7, 0xd0, 0x9c, 0x9d, 0x4d, 0x2b, 0xf2, 0x6a, 0x6e, 0xc1, 0xc6, 0xf1, 0x35,
	0x19, 0xdf, 0x9e, 0x04, 0xa2, 0x0b, 0x1c, 0xd5, 0x97, 0xe6, 0x7f, 0x34, 0xd8, 0x9c, 0x95, 0xab,
	0xde, 0xda, 0x85, 0xba, 0x98, 0x22, 0x16, 0x89, 0xe5, 0x32, 0x58, 0x05, 0xd7, 0x84, 0x4c, 0x99,
	0xa2, 0x9f, 0xc0, 0x7a, 0x38, 0x1d, 0x79, 0x2e, 0xbb, 0x26, 0x51, 0x6a, 0x17, 0xf7, 0x5b, 0x2b,
	0x55, 0x24, 0xc6, 0xcf, 0x21, 0x5f, 0xd3, 0xa9, 0x79, 0x49, 0x9a, 0xa3, 0x9c, 0x2a, 0x71, 0x30,
	0x01, 0x52, 0xc2, 0x63, 0x6d, 0x43, 0x90, 0x8c, 0xfc, 0x13, 0x26, 0x27, 0x15, 0x7f, 0x90, 0x65,
	0x3c, 0x2f, 0x36, 0x64, 0xc1, 0x44, 0x90, 0x12, 0x3d, 0x33, 0xbf, 0x81, 0xb6, 0x7c, 0xdd, 0x32,
	0x4a, 0x9a, 0x73, 0xd6, 0x16, 0x9c, 0x7f, 0xaf, 0xc1, 0xa7, 0x4b, 0xbc, 0x55, 0x82, 0xe6, 0xc8,
	0x54, 0x7b, 0x10, 0x99, 0xa2, 0x67, 0x50, 0x8e, 0xe9, 0x38, 0xe6, 0xcd, 0xc5, 0x6d, 0x41, 0x7a,
	0x24, 0x36, 0xfb, 0xdf, 0x42, 0x59, 0x4d, 0x36, 0x54, 0x83, 0xf2, 0xe0, 0xd2, 0xc2, 0xaf, 0x5f,
	0x9f, 0xb5, 0x0a, 0xa8, 0x05, 0xf5, 0xc1, 0xa5, 0x75, 0x71, 0xd5, 0x3d, 0xed, 0x0f, 0x7b, 0x27,
	0xb8, 0x25, 0x4a, 0xb5, 0x29, 0x24, 0x1d, 0x7c, 0xd9, 0x3f, 0xee, 0x5f, 0x74, 0xce, 0x2f, 0x5b,
	0xfa, 0xfe, 0x33, 0xa8, 0xcf, 0xb4, 0x40, 0x0b, 0xea, 0x6f, 0x87, 0x56, 0xe7, 0xb7, 0x9d, 0xfe,
	0x69, 0xa7, 0x7b, 0x7a, 0xd2, 0x2a, 0x88, 0xa0, 0x6f, 0x87, 0xd6, 0xcb, 0xab, 0xd3, 0xd3, 0x96,
	0xb6, 0x3f, 0x80, 0x6a, 0xd6, 0x9e, 0x4d, 0x80, 0xc1, 0xd0, 0xba, 0x38, 0x39, 0xff, 0xbe, 0x7f,
	0xfe, 0x9b, 0x56, 0x41, 0x9d, 0xf1, 0xd5, 0xf9, 0xb9, 0x38, 0x6b, 0xea, 0x3c, 0xbc, 0x3a, 0x3e,
	0x3e, 0x19, 0x0e, 0x5b, 0x3a, 0x6a, 0x40, 0x75, 0x30, 0xb4, 0x5e, 0x76, 0xfa, 0xa7, 0x27, 0xdf,
	0xb7, 0x8c, 0xc3, 0xbf, 0x69, 0x50, 0xef, 0x88, 0x54, 0x8a, 0x3c, 0xb8, 0x63, 0x82, 0x5e, 0x41,
	0x3d, 0x5f, 0x67, 0x28, 0x5b, 0xec, 0x96, 0x94, 0xe5, 0xf6, 0x93, 0x15, 0x5a, 0x95, 0xfb, 0x77,
	0xb0, 0xbe, 0x00, 0x0c, 0xda, 0x9d, 0xf5, 0x59, 0x02, 0xf9, 0xb6, 0xf9, 0x31, 0x93, 0x38, 0x76,
	0xf7, 0xe5, 0xbb, 0xaf, 0x26, 0x2e, 0xbf, 0x9e, 0x8e, 0x0e, 0xc6, 0xd4, 0x7f, 0xae, 0xec, 0x9f,
	0xcb, 0x7f, 0x0c, 0x8c, 0xa9, 0x97, 0x08, 0xfe, 0xaa, 0x37, 0x4e, 0xdd, 0x3b, 0xf2, 0x4a, 0x0c,
	0x71, 0xa1, 0xfa, 0xaf, 0xde, 0x54, 0xe7, 0xa3, 0x23, 0x29, 0x18, 0xad, 0x49, 0x97, 0x9f, 0xff,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x54, 0x7f, 0x00, 0x36, 0x81, 0x10, 0x00, 0x00,
}
